# Generated by Django 5.0.6 on 2024-06-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='price',
        ),
    ]
