# Generated by Django 5.0.6 on 2024-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(max_length=200, null=True, upload_to='products/'),
        ),
    ]
