# Generated by Django 5.0.6 on 2024-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='otherInfo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
