# Generated by Django 5.0.6 on 2024-08-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_category_products_otherinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
    ]
